# Generated by Django 3.2.5 on 2022-03-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('phone', models.IntegerField(max_length=50)),
                ('media', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
